on: [push]

jobs:
  checks:
    runs-on: ubuntu-latest
    name: Create distribution
    strategy:
      matrix:
        pl: [
        458, 459, 460, 461, 462, 463, 464,
        465, 466, 467, 468, 469, 470, 471,
        472, 473, 474, 475, 476, 477, 478, 479
        ]
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: configure aws cli for s3 uploads
        run: |
          pip install awscli-plugin-endpoint

          mkdir ~/.aws
          cat > ~/.aws/config <<CONF
          [plugins]
          endpoint = awscli_plugin_endpoint

          [default]
          region = ${SCW_REGION}
          s3 =
            endpoint_url = https://s3.fr-par.scw.cloud
            signature_version = s3v3
          s3api =
            endpoint_url = https://s3.fr-par.scw.cloud
          CONF
          cat > ~/.aws/credentials <<CREDS
          [default]
          aws_access_key_id = ${{ secrets.SCW_ACCESS_KEY_ID }}
          aws_secret_access_key = ${{ secrets.SCW_SECRET_KEY }}
          CREDS

          aws s3 ls s3://asjackson-211bsd-ci/

      - name: Create root.dump
        uses: AaronJackson/2.11BSD-Action@main
        with:
          path: /dist
          patch_level: ${{ matrix.pl }}
          run: |
            rm -rf /olddev /genunix /unixold /netnix
            cd /usr/src/sys/GENERIC
            make
            make install

            cd /dev
            ./MAKEDEV ra1
            mkfs -s 10240 /dev/ra1a

            cp /usr/bin/sleep /bin/sleep
            rm -rf /usr /disklabel
            rm /*.core || true
            rm -rf /tmp/* || true
            rm /bin/*.old || true
            rm -rf /dist || true

            cd /
            mount /dev/ra1a /mnt
            dump 0f /mnt/root.dump / || true
            chmod 644 /mnt/root.dump
            sync
            sleep 10
            umount /mnt

      - name: Extract root.dump
        run: |
          mkdir distribution scratch
          sudo chown $USER: -R scratch ../scratch.dsk
          bsd211fs ../scratch.dsk scratch
          cp scratch/root.dump distribution/root.dump
          umount scratch
          ls -lah distribution
          gzip distribution/root.dump
          sleep 5
          aws --debug s3 cp distribution/root.dump.gz s3://asjackson-211bsd-ci/dist-${{ matrix.pl }}-root.dump.gz
          rm -f ../ci.dsk

      - name: Create file6.tar (/usr excluding /usr/src as a tar dump)
        uses: AaronJackson/2.11BSD-Action@main
        with:
          path: /dist
          patch_level: ${{ matrix.pl }}
          run: |
            cd /dev
            ./MAKEDEV ra1
            mkfs -s 102400 /dev/ra1a
            cd /
            mount /dev/ra1a /mnt
            cd /usr
            rm -rf src
            tar cf - . > /mnt/file6.tar
            chmod 644 /mnt/file6.tar

      - name: Extract file6.tar
        run: |
          mkdir distribution scratch
          sudo chown $USER: -R scratch ../scratch.dsk
          bsd211fs ../scratch.dsk scratch
          cp scratch/file6.tar distribution/file6.tar
          gzip distribution/file6.tar
          umount scratch
          ls -lah distribution
          aws s3 cp distribution/file6.tar.gz s3://asjackson-211bsd-ci/dist/${{ matrix.pl }}/file6.tar.gz
          rm -f ../ci.dsk

      - name: Create file7.tar (/usr/src/include and /usr/src/sys as a tar dump)
        uses: AaronJackson/2.11BSD-Action@main
        with:
          path: /dist
          patch_level: ${{ matrix.pl }}
          run: |
            cd /dev
            ./MAKEDEV ra1
            mkfs -s 102400 /dev/ra1a
            cd /
            mount /dev/ra1a /mnt
            cd /usr/src
            tar cf - sys include > /mnt/file7.tar
            chmod 644 /mnt/file7.tar

      - name: Extract file7.tar
        run: |
          mkdir distribution scratch
          sudo chown $USER: -R scratch ../scratch.dsk
          bsd211fs ../scratch.dsk scratch
          cp scratch/file7.tar distribution/file7.tar
          gzip distribution/file7.tar
          umount scratch
          ls -lah distribution
          aws s3 cp distribution/file7.tar.gz s3://asjackson-211bsd-ci/dist/${{ matrix.pl }}/file7.tar.gz
          rm -f ../ci.dsk

      - name: Create file8.tar (/usr/src excluding sys and include as a tar dump)
        uses: AaronJackson/2.11BSD-Action@main
        with:
          path: /dist
          patch_level: ${{ matrix.pl }}
          run: |
            cd /dev
            ./MAKEDEV ra1
            mkfs -s 102400 /dev/ra1a
            cd /
            mount /dev/ra1a /mnt
            cd /usr/src
            rm -rf sys include
            tar cf - . > /mnt/file8.tar
            chmod 644 /mnt/file8.tar

      - name: Extract file8.tar
        run: |
          mkdir distribution scratch
          sudo chown $USER: -R scratch ../scratch.dsk
          bsd211fs ../scratch.dsk scratch
          cp scratch/file8.tar distribution/file8.tar
          gzip distribution/file8.tar
          umount scratch
          ls -lah distribution
          aws s3 cp distribution/file8.tar.gz s3://asjackson-211bsd-ci/dist/${{ matrix.pl }}/file8.tar.gz
          rm -f ../ci.dsk
