on: [push]

jobs:
  checks:
    runs-on: ubuntu-latest
    name: Create distribution
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Create root.dump
        uses: AaronJackson/2.11BSD-Action@main
        with:
          path: /dist
          patch_level: 479
          run: |
            rm -rf /olddev /genunix /unixold /netnix
            cd /usr/src/sys/GENERIC
            make
            make install

            cd /dev
            ./MAKEDEV ra1
            mkfs -s 10240 /dev/ra1a

            cp /usr/bin/sleep /bin/sleep
            rm -rf /usr /disklabel
            rm /*.core || true
            rm -rf /tmp/* || true
            rm /bin/*.old || true
            rm -rf /dist || true

            strip /boot /toyset /bin/* /sbin/* || true

            cd /
            mount /dev/ra1a /mnt
            dump 0f /mnt/root.dump / || true
            chmod 644 /mnt/root.dump
            sync
            sleep 10
            umount /mnt

      - name: Extract root.dump
        run: |
          mkdir distribution scratch
          sudo chown $USER: -R scratch ../scratch.dsk
          bsd211fs ../scratch.dsk scratch
          cp scratch/root.dump distribution/root.dump
          umount scratch
          ls -lah distribution

      - name: Create file6.tar (/usr excluding /usr/src as a tar dump)
        uses: AaronJackson/2.11BSD-Action@main
        with:
          path: /dist
          patch_level: 479
          run: |
            cd /dev
            ./MAKEDEV ra1
            mkfs -s 10240 /dev/ra1a
            cd /
            mount /dev/ra1a /mnt
            cd /usr
            rm -rf src
            tar cf - . > /mnt/file6.tar


      - name: Extract file6.tar
        run: |
          mkdir distribution scratch
          sudo chown $USER: -R scratch ../scratch.dsk
          bsd211fs ../scratch.dsk scratch
          cp scratch/file6.tar distribution/file6.tar
          gzip distribution/file6.tar
          umount scratch
          ls -lah distribution
